import { PrismaClient } from "@prisma/client";
import { calculateScores } from "../app/utils/score.server";

const prisma = new PrismaClient();

const initialCars = [
  {
    brand: "Fiat",
    model: "Fastback",
    year: 2024,
    price_avg: 135990,
    type: "SUV",
    imageUrl: "https://vrum.com.br/wp-content/uploads/2022/09/fiat-fastback-impulse-t200-preto.jpg",
    spec: {
      trunk_liters: 600,
      wheelbase: 2.53,
      ground_clearance: 192,
      fuel_consumption_city: 11.3,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 130,
      acceleration: 8.1,
    },
  },
  {
    brand: "Volkswagen",
    model: "T-Cross",
    year: 2024,
    price_avg: 145990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/171501311/model_main_comprar-t-cross-comfortline-200-tsi-ad7a97682d_44a9544bc3.png",
    spec: {
      trunk_liters: 373,
      wheelbase: 2.65,
      ground_clearance: 190,
      fuel_consumption_city: 11.0,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 128,
      acceleration: 10.2,
    },
  },
  {
    brand: "Volkswagen",
    model: "Polo",
    year: 2024,
    price_avg: 89990,
    type: "Hatch",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/148011111/model_main_comprar-polo-track-1-0-mpi-2024-e5d8a9e6af_8c6a5e1d3d.png",
    spec: {
      trunk_liters: 300,
      wheelbase: 2.56,
      ground_clearance: 149,
      fuel_consumption_city: 13.5,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 84,
      acceleration: 13.4,
    },
  },
  {
    brand: "Fiat",
    model: "Strada",
    year: 2024,
    price_avg: 110990,
    type: "Picape",
    imageUrl: "https://api.fiat.com.br/image-magick/imagem/strada_preto.png",
    spec: {
      trunk_liters: 844,
      wheelbase: 2.73,
      ground_clearance: 208,
      fuel_consumption_city: 11.7,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 107,
      acceleration: 11.6,
    },
  },
  {
    brand: "Hyundai",
    model: "HB20",
    year: 2024,
    price_avg: 82990,
    type: "Hatch",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/152011111/model_main_comprar-hb20-sense-2024-d5e8a9f6af_7b6a5e2d3d.png",
    spec: {
      trunk_liters: 300,
      wheelbase: 2.53,
      ground_clearance: 160,
      fuel_consumption_city: 13.3,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 80,
      acceleration: 14.5,
    },
  },
  {
    brand: "Chevrolet",
    model: "Onix",
    year: 2024,
    price_avg: 85990,
    type: "Hatch",
    imageUrl: "https://quatrorodas.abril.com.br/wp-content/uploads/2019/11/onix-hatch-premier-2020-01.jpg",
    spec: {
      trunk_liters: 275,
      wheelbase: 2.55,
      ground_clearance: 128,
      fuel_consumption_city: 13.9,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 82,
      acceleration: 13.3,
    },
  },
  {
    brand: "Jeep",
    model: "Compass",
    year: 2024,
    price_avg: 184990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/165011111/model_main_comprar-compass-sport-2024-a5d8a9e6af_9c6a5e1d3d.png",
    spec: {
      trunk_liters: 476,
      wheelbase: 2.63,
      ground_clearance: 205,
      fuel_consumption_city: 10.5,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 185,
      acceleration: 8.8,
    },
  },
  {
    brand: "Toyota",
    model: "Corolla",
    year: 2024,
    price_avg: 148990,
    type: "Sedan",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/142011111/model_main_comprar-corolla-gli-2024-f5d8a9e6af_6c6a5e1d3d.png",
    spec: {
      trunk_liters: 470,
      wheelbase: 2.70,
      ground_clearance: 148,
      fuel_consumption_city: 11.6,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 177,
      acceleration: 9.2,
    },
  },
  {
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    price_avg: 135990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/155011111/model_main_comprar-creta-comfort-2024-e5d8a9e6af_8c6a5e1d3d.png",
    spec: {
      trunk_liters: 422,
      wheelbase: 2.61,
      ground_clearance: 190,
      fuel_consumption_city: 11.6,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 120,
      acceleration: 11.5,
    },
  },
  {
    brand: "Nissan",
    model: "Kicks",
    year: 2024,
    price_avg: 125990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/162011111/model_main_comprar-kicks-active-2024-d5e8a9f6af_7b6a5e2d3d.png",
    spec: {
      trunk_liters: 432,
      wheelbase: 2.62,
      ground_clearance: 200,
      fuel_consumption_city: 11.4,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 114,
      acceleration: 11.4,
    },
  },
  {
    brand: "Jeep",
    model: "Renegade",
    year: 2024,
    price_avg: 129990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/168011111/model_main_comprar-renegade-1-3-turbo-2024-c5d8a9e6af_5c6a5e1d3d.png",
    spec: {
      trunk_liters: 320,
      wheelbase: 2.57,
      ground_clearance: 185,
      fuel_consumption_city: 9.5,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 185,
      acceleration: 8.7,
    },
  },
  {
    brand: "Honda",
    model: "HR-V",
    year: 2024,
    price_avg: 151990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/145011111/model_main_comprar-hr-v-ex-2024-b5d8a9e6af_8c6a5e1d3d.png",
    spec: {
      trunk_liters: 354,
      wheelbase: 2.61,
      ground_clearance: 188,
      fuel_consumption_city: 12.7,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 126,
      acceleration: 11.2,
    },
  },
  {
    brand: "Toyota",
    model: "Corolla Cross",
    year: 2024,
    price_avg: 164990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/143011111/model_main_comprar-corolla-cross-xr-2024-a5d8a9e6af_9c6a5e1d3d.png",
    spec: {
      trunk_liters: 440,
      wheelbase: 2.64,
      ground_clearance: 161,
      fuel_consumption_city: 11.7,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 177,
      acceleration: 9.8,
    },
  },
  {
    brand: "Chevrolet",
    model: "Tracker",
    year: 2024,
    price_avg: 130990,
    type: "SUV",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/158011111/model_main_comprar-tracker-1-2-turbo-2024-f5d8a9e6af_6c6a5e1d3d.png",
    spec: {
      trunk_liters: 393,
      wheelbase: 2.57,
      ground_clearance: 157,
      fuel_consumption_city: 11.2,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 132,
      acceleration: 10.5,
    },
  },
  {
    brand: "Fiat",
    model: "Mobi",
    year: 2024,
    price_avg: 71990,
    type: "Hatch",
    imageUrl: "https://api.fiat.com.br/image-magick/imagem/mobi_branco.png",
    spec: {
      trunk_liters: 215,
      wheelbase: 2.30,
      ground_clearance: 190,
      fuel_consumption_city: 13.5,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 74,
      acceleration: 14.4,
    },
  },
  {
    brand: "Renault",
    model: "Kwid",
    year: 2024,
    price_avg: 72990,
    type: "Hatch",
    imageUrl: "https://production.autoforce.com/uploads/picture/image/159011111/model_main_comprar-kwid-zen-2024-e5d8a9e6af_8c6a5e1d3d.png",
    spec: {
      trunk_liters: 290,
      wheelbase: 2.42,
      ground_clearance: 185,
      fuel_consumption_city: 15.3,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 71,
      acceleration: 13.2,
    },
  },
  {
    brand: "BYD",
    model: "Dolphin",
    year: 2024,
    price_avg: 149800,
    type: "Hatch",
    imageUrl: "https://diariodocomercio.com.br/wp-content/uploads/2023/12/byd-dolphin.jpg",
    spec: {
      trunk_liters: 345,
      wheelbase: 2.70,
      ground_clearance: 120,
      fuel_consumption_city: 20.0, // Electric equivalent
      fuel_type: "Elétrico",
      transmission: "Automático",
      hp: 95,
      acceleration: 10.9,
    },
  },
];

async function main() {
  console.log("Start seeding ...");
  await prisma.car.deleteMany({});
  for (const car of initialCars) {
    const createdCar = await prisma.car.create({
      data: {
        brand: car.brand,
        model: car.model,
        year: car.year,
        price_avg: car.price_avg,
        type: car.type,
        imageUrl: car.imageUrl,
        spec: {
          create: {
            ...car.spec,
            ...calculateScores(car.spec),
          },
        },
      },
    });
    console.log(`Created car with id: ${createdCar.id}`);
  }
  console.log("Seeding finished.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
