import { PrismaClient } from "@prisma/client";
import { calculateScores } from "../app/utils/score.server";

const prisma = new PrismaClient();

const initialCars = [
  {
    brand: "Fiat",
    model: "Fastback",
    year: 2024,
    price_avg: 135990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Fiat_Fastback_Audace_T200.jpg/800px-Fiat_Fastback_Audace_T200.jpg",
    spec: {
      trunk_liters: 600,
      wheelbase: 2.53,
      ground_clearance: 192,
      fuel_consumption_city: 11.3,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 130,
      acceleration: 8.1,
    },
  },
  {
    brand: "Volkswagen",
    model: "T-Cross",
    year: 2024,
    price_avg: 145990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Volkswagen_T-Cross_R-Line_%28C1%29_%E2%80%93_Frontansicht%2C_28._September_2019%2C_D%C3%BCsseldorf.jpg/800px-Volkswagen_T-Cross_R-Line_%28C1%29_%E2%80%93_Frontansicht%2C_28._September_2019%2C_D%C3%BCsseldorf.jpg",
    spec: {
      trunk_liters: 373,
      wheelbase: 2.65,
      ground_clearance: 190,
      fuel_consumption_city: 11.0,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 128,
      acceleration: 10.2,
    },
  },
  {
    brand: "Volkswagen",
    model: "Polo",
    year: 2024,
    price_avg: 89990,
    type: "Hatch",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/2021_Volkswagen_Polo_Life.jpg/800px-2021_Volkswagen_Polo_Life.jpg",
    spec: {
      trunk_liters: 300,
      wheelbase: 2.56,
      ground_clearance: 149,
      fuel_consumption_city: 13.5,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 84,
      acceleration: 13.4,
    },
  },
  {
    brand: "Fiat",
    model: "Strada",
    year: 2024,
    price_avg: 110990,
    type: "Picape",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Fiat_Strada_Volcano_1.3_2021_front_view.jpg/800px-Fiat_Strada_Volcano_1.3_2021_front_view.jpg",
    spec: {
      trunk_liters: 844,
      wheelbase: 2.73,
      ground_clearance: 208,
      fuel_consumption_city: 11.7,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 107,
      acceleration: 11.6,
    },
  },
  {
    brand: "Hyundai",
    model: "HB20",
    year: 2024,
    price_avg: 82990,
    type: "Hatch",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Hyundai_HB20_facelift_in_Montevideo_%28cropped%29.jpg/800px-Hyundai_HB20_facelift_in_Montevideo_%28cropped%29.jpg",
    spec: {
      trunk_liters: 300,
      wheelbase: 2.53,
      ground_clearance: 160,
      fuel_consumption_city: 13.3,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 80,
      acceleration: 14.5,
    },
  },
  {
    brand: "Chevrolet",
    model: "Onix",
    year: 2024,
    price_avg: 85990,
    type: "Hatch",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Chevrolet_Onix_Premier_2020.jpg/800px-Chevrolet_Onix_Premier_2020.jpg",
    spec: {
      trunk_liters: 275,
      wheelbase: 2.55,
      ground_clearance: 128,
      fuel_consumption_city: 13.9,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 82,
      acceleration: 13.3,
    },
  },
  {
    brand: "Jeep",
    model: "Compass",
    year: 2024,
    price_avg: 184990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Jeep_Compass_MHEV_IAA_2021_1X7A0307.jpg/800px-Jeep_Compass_MHEV_IAA_2021_1X7A0307.jpg",
    spec: {
      trunk_liters: 476,
      wheelbase: 2.63,
      ground_clearance: 205,
      fuel_consumption_city: 10.5,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 185,
      acceleration: 8.8,
    },
  },
  {
    brand: "Toyota",
    model: "Corolla",
    year: 2024,
    price_avg: 148990,
    type: "Sedan",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/2020_Toyota_Corolla_Altis_1.8_G_ZRE211R_%2820200228%29.jpg/800px-2020_Toyota_Corolla_Altis_1.8_G_ZRE211R_%2820200228%29.jpg",
    spec: {
      trunk_liters: 470,
      wheelbase: 2.70,
      ground_clearance: 148,
      fuel_consumption_city: 11.6,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 177,
      acceleration: 9.2,
    },
  },
  {
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    price_avg: 135990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/2022_Hyundai_Creta_1.5_Prime_%28Indonesia%29_front_view.jpg/800px-2022_Hyundai_Creta_1.5_Prime_%28Indonesia%29_front_view.jpg",
    spec: {
      trunk_liters: 422,
      wheelbase: 2.61,
      ground_clearance: 190,
      fuel_consumption_city: 11.6,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 120,
      acceleration: 11.5,
    },
  },
  {
    brand: "Nissan",
    model: "Kicks",
    year: 2024,
    price_avg: 125990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Nissan_Kicks_%28P15%29_facelift_IMG_4366.jpg/800px-Nissan_Kicks_%28P15%29_facelift_IMG_4366.jpg",
    spec: {
      trunk_liters: 432,
      wheelbase: 2.62,
      ground_clearance: 200,
      fuel_consumption_city: 11.4,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 114,
      acceleration: 11.4,
    },
  },
  {
    brand: "Jeep",
    model: "Renegade",
    year: 2024,
    price_avg: 129990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/2019_Jeep_Renegade_Limited_1.0_Front.jpg/800px-2019_Jeep_Renegade_Limited_1.0_Front.jpg",
    spec: {
      trunk_liters: 320,
      wheelbase: 2.57,
      ground_clearance: 185,
      fuel_consumption_city: 9.5,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 185,
      acceleration: 8.7,
    },
  },
  {
    brand: "Honda",
    model: "HR-V",
    year: 2024,
    price_avg: 151990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/2022_Honda_HR-V_1.5_E_CVT_%28Indonesia%29_front_view.jpg/800px-2022_Honda_HR-V_1.5_E_CVT_%28Indonesia%29_front_view.jpg",
    spec: {
      trunk_liters: 354,
      wheelbase: 2.61,
      ground_clearance: 188,
      fuel_consumption_city: 12.7,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 126,
      acceleration: 11.2,
    },
  },
  {
    brand: "Toyota",
    model: "Corolla Cross",
    year: 2024,
    price_avg: 164990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/2021_Toyota_Corolla_Cross_1.8_V_ZSG10_%2820210403%29.jpg/800px-2021_Toyota_Corolla_Cross_1.8_V_ZSG10_%2820210403%29.jpg",
    spec: {
      trunk_liters: 440,
      wheelbase: 2.64,
      ground_clearance: 161,
      fuel_consumption_city: 11.7,
      fuel_type: "Flex",
      transmission: "CVT",
      hp: 177,
      acceleration: 9.8,
    },
  },
  {
    brand: "Chevrolet",
    model: "Tracker",
    year: 2024,
    price_avg: 130990,
    type: "SUV",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Chevrolet_Tracker_Premier_1.2_Turbo_2021.jpg/800px-Chevrolet_Tracker_Premier_1.2_Turbo_2021.jpg",
    spec: {
      trunk_liters: 393,
      wheelbase: 2.57,
      ground_clearance: 157,
      fuel_consumption_city: 11.2,
      fuel_type: "Flex",
      transmission: "Automático",
      hp: 132,
      acceleration: 10.5,
    },
  },
  {
    brand: "Fiat",
    model: "Mobi",
    year: 2024,
    price_avg: 71990,
    type: "Hatch",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Fiat_Mobi_Like_2021.jpg/800px-Fiat_Mobi_Like_2021.jpg",
    spec: {
      trunk_liters: 215,
      wheelbase: 2.30,
      ground_clearance: 190,
      fuel_consumption_city: 13.5,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 74,
      acceleration: 14.4,
    },
  },
  {
    brand: "Renault",
    model: "Kwid",
    year: 2024,
    price_avg: 72990,
    type: "Hatch",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Renault_Kwid_Intense_2022_front.jpg/800px-Renault_Kwid_Intense_2022_front.jpg",
    spec: {
      trunk_liters: 290,
      wheelbase: 2.42,
      ground_clearance: 185,
      fuel_consumption_city: 15.3,
      fuel_type: "Flex",
      transmission: "Manual",
      hp: 71,
      acceleration: 13.2,
    },
  },
  {
    brand: "BYD",
    model: "Dolphin",
    year: 2024,
    price_avg: 149800,
    type: "Hatch",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/BYD_Dolphin_IAA_2023_1X7A0063.jpg/800px-BYD_Dolphin_IAA_2023_1X7A0063.jpg",
    spec: {
      trunk_liters: 345,
      wheelbase: 2.70,
      ground_clearance: 120,
      fuel_consumption_city: 20.0, // Electric equivalent
      fuel_type: "Elétrico",
      transmission: "Automático",
      hp: 95,
      acceleration: 10.9,
    },
  },
];

async function main() {
  console.log("Start seeding ...");
  await prisma.car.deleteMany({});
  for (const car of initialCars) {
    const createdCar = await prisma.car.create({
      data: {
        brand: car.brand,
        model: car.model,
        year: car.year,
        price_avg: car.price_avg,
        type: car.type,
        imageUrl: car.imageUrl,
        spec: {
          create: {
            ...car.spec,
            ...calculateScores(car.spec),
          },
        },
      },
    });
    console.log(`Created car with id: ${createdCar.id}`);
  }
  console.log("Seeding finished.");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
